<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_mode_alter().
 * @param $view_mode
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param $context
 */
function planck_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context)
{
    Drupal::service('planck.view_mode_handler')->entityViewModeAlter($view_mode, $entity, $context);
}

/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function planck_theme($existing, $type, $theme, $path)
{
    return Drupal::service('planck.theme_manager')->theme($existing, $type, $theme, $path);
}